### PR TITLE
Stop enabling notifications

### LINKED ISSUE #110: Stop enabling the notifications package
https://github.com/steelbrain/package-deps/blob/4e705d8d2b1bd13e72f8319b03fc0116c217e496/src/index.js#L21

There is no reason to enable the notifications package.

This causes issues when the user installs a different package for notifications.

[notifications-plus#2](https://github.com/UziTech/notifications/issues/2)

### PR DESCRIPTION
**Pull request by UziTech**
Let the user decide which package to display their notifications.

Fixes #110

### CODE REVIEW

**Comment by steelbrain** [comment]
Instead of removing the logic entirely, I'd be in favor of not enabling the package if `notifications-plus` or any other famous community packages are active

**Comment by UziTech** [comment]
I don't believe it would be a good idea to hard-code package names that could be active.

Since the `notifications` package is a core package, and enabled by default, I don't believe there is any risk of a novice disabling it. Therefore, if the `notifications` package is disabled I would assume the user had a good reason for it.

**Comment by UziTech** [comment]
`atom.notifications.add*` still works when the `notifications` package is disabled so this shouldn't error out anyway.

**Comment by Arcanemagus** [comment]
The problem is that some users disable it just because they can ("why would I need this?!"), without bothering to install a replacement.

**Comment by UziTech** [comment]
If a user is going to disable the `notifications` package then one of two things is going to happen:

  1. They don't want **any** notifications. So we should respect their choice.
  2. Not having `notifications` enabled is going to be one of their least worries because they are likely to disable something else more important.

**Comment by UziTech** [comment]
That would be the same thing as Atom enabling the `find-and-replace` anytime someone pressed <kbd>ctrl</kbd> + <kbd>f</kbd> just incase they accidentally disabled it.

**Comment by UziTech** [comment]
any update on this?

**Comment by UziTech** [comment]
Seriously this is very annoying. @steelbrain Any reason this is not going anywhere?

**Comment by steelbrain** [comment]
@UziTech Apologies for the delay. This package is practically useless without the notifications package since in the latest update, every install requires confirmation. I would much much prefer to hard-code community notifications packages instead of not enabling the stock one

**Comment by UziTech** [comment]
I guess that would be better than nothing but again I think the argument that someone would "accidentally" disable the notifications package, or not realize atom can't notify them if they disable the notifications package is absurd.

I understand that this package requires the user to be notified in order to be functional. I just don't see any case where a user would disable the notifications package and still want this package to notify them through the notifications package.

I think a better option (although maybe still a bit annoying) would be to write something to the console if the notifications package is disabled. The first thing a developer is going to do if a package doesn't work is open the console and check for errors.

**Comment by Arcanemagus** [comment]
> I understand that this package requires the user to be notified in order to be functional.
> I think a better option (although maybe still a bit annoying) would be to write something to the console if the notifications package is disabled.

Personally I'd say that's a great idea: If notifications can't be sent, at least there is a record somewhere of what was attempted. If the user purposely broke things they really have nobody but themselves to blame.

**Comment by steelbrain** [comment]
Count me in on that too. It sounds reasonable. @UziTech Could you please update this PR to reflect the changes?

**Pull request merged**
