### PR TITLE
feat: add support for prompt-less installation

### PR DESCRIPTION
**Pull request by aminya**
Fixes https://github.com/steelbrain/package-deps/issues/319

### CODE REVIEW

**Comment by aminya** [comment]
@steelbrain Could you merge this?

**Comment by steelbrain** [comment]
Can you apply this patch? Apply it and we're off to the races!
[patch.txt](https://github.com/steelbrain/package-deps/files/5818933/patch.txt)

**Comment by aminya** [comment]
@steelbrain Here you go!

**Comment by steelbrain** [comment]
Thank you for working on this!

**Comment by aminya** [comment]
> Thank you for working on this!

You're welcome!

**Comment by steelbrain** [comment]
Published in atom-package-deps@7.1.0

**Pull request merged**
