### PR TITLE
Lazy load

### PR DESCRIPTION
**Pull request by aminya**
- Using Rollup and dynamic imports:
- I separated/refactored the part that checks if package-deps are installed from the part that installs the package-deps
- the whole check part is bundled into a single file and will be always loaded
- the install/prompt part is only loaded on demand.
 
Because many packages depend on package-deps, I think this optimization will benefit the whole Atom ecosystem.

This is tested and works as expected. It reduces the load time of a test package by **12ms** (using `require("atom-package-deps").install`):
before
2020-05-05 22_33_27-Timecop — C__Users_yahyaaba_Documents_GitHub_JavaScript_atom-ide-community_atom-
after
2020-05-05 22_37_29-Timecop — C__Users_yahyaaba_Documents_GitHub_JavaScript_atom-ide-community_atom-

Small other changes:
- I did not change any of the helper codes. I just moved them to separate files.
- use files in package.json instead of putting every folder in npmignore
- renamed `compile` in scripts to `debug`

### CODE REVIEW

**Comment by aminya** [comment]
Any feedback on this? This is ready

**Comment by steelbrain** [comment]
Thank you for working on this, looks good, I'll review/merge this weekend

**Comment by aminya** [comment]
By targeting electron 5, package-deps is now even faster.

**Comment by aminya** [comment]
@steelbrain Any update on this? This is a small change. I just moved the code to different files, and I used dynamic import in the main file.

**Comment by steelbrain** [comment]
I'll review within the next 24 hours :)

**Comment by steelbrain** [comment]
Applied some touchups in https://github.com/steelbrain/package-deps/pull/281

**Comment by aminya** [comment]
Awesome!

**Pull request merged**
