### PR TITLE
Fix progress bar

### PR DESCRIPTION
**Pull request by steelbrain**
Fixes https://github.com/steelbrain/package-deps/issues/17
Ref: facebook/nuclide#184

I have personally confirmed that it works. But a test case would've been better. The more I think about it, the more I feel the need to write some tests. but I haven't been able to put together enough time for it yet, unfortunately :(

### CODE REVIEW

**Comment by joefitzgerald** [comment]
> The more I think about it, the more I feel the need to write some tests. but I haven't been able to put together enough time for it yet, unfortunately :(

Your issue is that you are not writing tests first. No tests = I don't think this should be used for anything linter-related.

**Comment by steelbrain** [comment]
@joefitzgerald so I tried to write unit tests, turns out that it's not that easy. `package-deps` uses the atom APIs to check for module metadata (and then it's deps) and the availability of it. so If I bundle a small module with it in the test runner, it won't work at all. because atom won't load a package that's not in its `~/.atom/packages`. If i install a package using apm cli and activate it afterwards, I would have no idea if it's done or still installing.

**Comment by joefitzgerald** [comment]
You need to learn to use Jasmine spies.

**Comment by steelbrain** [comment]
@joefitzgerald Yep! I just read them today in the dcs, but I don't think they solve the problem of loading packages that are not in `~/.atom/packages` :(

**Pull request merged**
